### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by davirezendemota** [countfy/countfy#1]

**Comment by tomast1337** [comment]
I've just spotted a few mistakes I have made in the Docker Compose file. I'm submitting #13  with these fixes.

**Comment by tomast1337** [comment]
I don't know if there will be any more problems with the frontend.
@davirezendemota

**Comment by davirezendemota** [comment]
@tomast1337 nice, i haven't handled the docker enviroment for the frontend yet, if some problem appears i'll reach you
